let res = {
  result: "SUCCESS",
  message: [
    {
      newSaleCnt: 1211,
      declinesCnt: 1362,
      approvedPerc: "47.07",
      newSaleRev: "42677.84",
      rebillCnt: 0,
      rebillDeclinesCnt: 0,
      rebillApprovedPerc: "0.00",
      rebillRev: "0.00",
      salesTax: "1590.63",
      surcharge: "0.00",
      refundCnt: 148,
      refundRev: "-6853.90",
      expenses: "-3792.60",
      chargebackCnt: 0,
      chargebackRev: "0.00",
      chargebackPerc: "0.00",
      grossRevenue: "42677.84",
      netRevenue: "32031.34",
      currencySymbol: "$",
      id: 1,
      refundPerc: "16.06",
      expenseDetails: {
        discountPrice: "2000.18",
        shipDiscount: "0.00",
        newSaleProductCost: "0.00",
        rebillProductCost: "0.00",
        shippingCost: "0.00",
        monthlyFee: 0,
        txnFee: "2389.85",
        discountFee: "1402.75",
        cbFee: "0.00",
        rdrFee: "0.00",
        commission: "0.00",
      },
      campaign: "Lash Cosmetics Main Campaign",
    },
    {
      newSaleCnt: 4,
      declinesCnt: 1,
      approvedPerc: "80.00",
      newSaleRev: "152.14",
      rebillCnt: 0,
      rebillDeclinesCnt: 0,
      rebillApprovedPerc: "0.00",
      rebillRev: "0.00",
      salesTax: "2.99",
      surcharge: "0.00",
      refundCnt: 1,
      refundRev: "-87.69",
      expenses: "-6.71",
      chargebackCnt: 0,
      chargebackRev: "0.00",
      chargebackPerc: "0.00",
      grossRevenue: "152.14",
      netRevenue: "57.74",
      currencySymbol: "$",
      id: 6,
      refundPerc: "57.64",
      expenseDetails: {
        discountPrice: "0.00",
        shipDiscount: "0.00",
        newSaleProductCost: "0.00",
        rebillProductCost: "0.00",
        shippingCost: "0.00",
        monthlyFee: 0,
        txnFee: "0.90",
        discountFee: "5.81",
        cbFee: "0.00",
        rdrFee: "0.00",
        commission: "0.00",
      },
      campaign: "Lash Cosmetics VIP Campaign",
    },
    {
      newSaleCnt: 14,
      declinesCnt: 48,
      approvedPerc: "22.58",
      newSaleRev: "419.37",
      rebillCnt: 0,
      rebillDeclinesCnt: 0,
      rebillApprovedPerc: "0.00",
      rebillRev: "0.00",
      salesTax: "10.77",
      surcharge: "0.00",
      refundCnt: 0,
      refundRev: "0.00",
      expenses: "-57.02",
      chargebackCnt: 0,
      chargebackRev: "0.00",
      chargebackPerc: "0.00",
      grossRevenue: "419.37",
      netRevenue: "362.35",
      currencySymbol: "$",
      id: 9,
      refundPerc: "0.00",
      expenseDetails: {
        discountPrice: "0.00",
        shipDiscount: "0.00",
        newSaleProductCost: "0.00",
        rebillProductCost: "0.00",
        shippingCost: "0.00",
        monthlyFee: 0,
        txnFee: "16.30",
        discountFee: "40.72",
        cbFee: "0.00",
        rdrFee: "0.00",
        commission: "0.00",
      },
      campaign: "Lash Cosmetics PEG campaign",
    },
  ],
};

let finalValues = [];
let finalRefund = 0;
res.message.map((item) => (finalRefund += Number(item.refundRev)));
finalValues.push(finalRefund.toFixed(2));

console.log(finalValues);
