return {
  salesTotal: totalAmount.toFixed(2),
  initialSales,
  declined,
  declinePerc: declined / (initialSales + declined),
  partial,
  avgTicket: (totalAmount / initialSales).toFixed(2),
  rebillRevenue,
  rebillApprovedPerc,
  rebillRefundRev: Math.abs(rebillRefundRev),
  billableRebillRev: billableRebillRev ? billableRebillRev : 0,
  frontendRefundRev: refundedAmount,
  frontendRefundPerc: (refundedAmount / totalAmount).toFixed(4),
  rebillRefundPerc: rebillRefundPerc ? rebillRefundPerc : 0,
  chargebackCnt,
  initialVip,
  declinedVip,
  ccInitialVip,
  CCoptVip: (ccInitialVip / ccInitialSale).toFixed(4),
  ccInitialSale,
  ppInitialSale,
  ppInitialVip,
  PPoptVip: (ppInitialVip / ppInitialSale).toFixed(4),
  TotaloptPPCC: (initialVip / initialSales).toFixed(4),
  totalVip,
};
